# Generated by Django 5.1.1 on 2024-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='quantidade_venda',
            field=models.IntegerField(),
        ),
    ]
